name: ci-linux

# Trigger the workflow on push or pull request
on:
  # pull_request:
  #   branches: [master]
  push:
    paths:
      - '.github/workflows/ci-linux.yml'
      - 'stack.yaml'
      - '*.cabal'
      - 'app/**'
      - 'src/**'
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc:
          - '9.4'

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: actions/cache
          path: .github/actions/cache-always
          ref: v3

      # Tweak `action.yml` of `actions/cache@v3` to remove its `post-if`
      # condition, making it default to `post-if: always()`.
      - name: Set up actions/cache-always@v3
        run: |
          sed -i -e '/ post-if: /d' .github/actions/cache-always/action.yml

      - uses: haskell/actions/setup@v2
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: latest

      - name: Configure
        run: cabal configure --enable-tests --test-show-details=direct

      - name: Freeze
        run: cabal freeze

      - name: actions/cache-always@v3
        uses: ./.github/actions/cache-always
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-cabal-${{ hashFiles('cabal.project.freeze') }}
            ${{ runner.os }}-${{ matrix.ghc }}-cabal-

      - name: Build dependencies
        run: cabal build --only-dependencies

      - name: Build
        run: cabal build

      - name: Install
        run: cabal install

      - name: Test
        run: iban-test --pattern '$NF !~ /N4/'

# vim: nospell
